version: '3'
services:
    nginx:
      image: nginx
      container_name: nginx
      restart: always    #重启方案
      privileged: true  
      ports:    #端口映射
        - 80:80    
        - 443:443
      networks:
        - web
      volumes:
        - ./conf/conf.d:/etc/nginx/conf.d
        - ./conf/ssl:/etc/nginx/ssl
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ../project:/var/www
        - ./logs:/var/log/nginx
networks:
  web:
    external: true # 不创建network
        
