version: '3'
services:
    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql
      restart: always
      privileged: true
      ports:    #端口映射
        - 3306:3306    
      networks:
        - web
      volumes:
      - type: bind
        source: ./conf/my.cnf
        target: /etc/mysql/conf/my.cnf
        read_only: true
      - type: bind
        source: ./conf/conf.d
        target: /etc/mysql/conf.d
        read_only: true
      - type: bind
        source: ./logs
        target: /var/log/mysql
      - type: volume
        source: data
        target: /var/lib/mysql
      environment:
        -  MYSQL_ROOT_PASSWORD=root
volumes:
  data:
networks:
  web:
    external: true # 不创建network
        
